/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paybuc.gui;

/**
 *
 * @author Brandon
 */
public class Statistics extends javax.swing.JPanel {

    /**
     * Creates new form Statistics
     */
    public Statistics(String day ,String stat05,String stat14,String stat23,String stat32,String stat41,String stat50) {
        initComponents();     
        dayTitle.setText(day);
        this.stat05.setText(stat05);
        this.stat14.setText(stat14);
        this.stat23.setText(stat23);
        this.stat32.setText(stat32);
        this.stat41.setText(stat41);
        this.stat50.setText(stat50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dayTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stat05 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stat14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stat23 = new javax.swing.JLabel();
        stat32 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stat41 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stat50 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        dayTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dayTitle.setForeground(new java.awt.Color(0, 0, 0));
        dayTitle.setText("  Day");
        dayTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        add(dayTitle);
        dayTitle.setBounds(6, 6, 298, 31);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("0 Odd & 5 Even");
        add(jLabel2);
        jLabel2.setBounds(12, 49, 120, 21);

        stat05.setForeground(new java.awt.Color(0, 0, 0));
        stat05.setText(": 00 Draws");
        add(stat05);
        stat05.setBounds(145, 49, 140, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("1 Odd & 4 Even");
        add(jLabel4);
        jLabel4.setBounds(10, 70, 120, 21);

        stat14.setForeground(new java.awt.Color(0, 0, 0));
        stat14.setText(": 00 Draws");
        add(stat14);
        stat14.setBounds(145, 70, 140, 21);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("2 Odd & 3 Even");
        add(jLabel6);
        jLabel6.setBounds(10, 90, 120, 21);

        stat23.setForeground(new java.awt.Color(0, 0, 0));
        stat23.setText(": 00 Draws");
        add(stat23);
        stat23.setBounds(145, 90, 140, 21);

        stat32.setForeground(new java.awt.Color(0, 0, 0));
        stat32.setText(": 00 Draws");
        add(stat32);
        stat32.setBounds(145, 110, 140, 21);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("3 Odd & 2 Even");
        add(jLabel9);
        jLabel9.setBounds(10, 110, 120, 21);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("4 Odd & 1 Even");
        add(jLabel10);
        jLabel10.setBounds(10, 130, 120, 21);

        stat41.setForeground(new java.awt.Color(0, 0, 0));
        stat41.setText(": 00 Draws");
        add(stat41);
        stat41.setBounds(145, 130, 140, 21);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("5 Odd & 0 Even");
        add(jLabel12);
        jLabel12.setBounds(10, 150, 120, 21);

        stat50.setForeground(new java.awt.Color(0, 0, 0));
        stat50.setText(": 00 Draws");
        add(stat50);
        stat50.setBounds(145, 150, 140, 21);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayTitle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel stat05;
    private javax.swing.JLabel stat14;
    private javax.swing.JLabel stat23;
    private javax.swing.JLabel stat32;
    private javax.swing.JLabel stat41;
    private javax.swing.JLabel stat50;
    // End of variables declaration//GEN-END:variables
}
